server:
  port: ${PORT:0}

spring:
  application:
    name: og-facilities-ws

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

feign:
  hystrix:
    enabled: true

rate:
  buildTime: 2
  neededResources: 2