server:
  port: ${PORT:0}

spring:
  application:
    name: og-resources-ws

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

rate:
  resourceIncreaseRate: 1