server:
  port: ${PORT:0}

spring:
  application:
    name: og-users-ws
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:postgresql://localhost:5432/ogmsdatabase
      username: postgres
      password: password
      hikari:
        maximum-pool-size: 30
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

gateway:
  ip: mbp-przemek.home

token:
  expirationDays: 5
  jwt:
    secretKey: mays932rj023rf09342jr903h97g867g7B789g678bv78B8b87b786B78bmays932rj023rf09342jr903h97g867g7B789g678bv78B8b87b786B78bmays932rj023rf09342jr903h97g867g7B789g

feign:
  hystrix:
    enabled: true